// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password, is_admin FROM users
WHERE email = $1 LIMIT 1
`

type GetUserByEmailRow struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Email    string    `json:"email"`
	Password string    `json:"password"`
	IsAdmin  int16     `json:"is_admin"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.IsAdmin,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, password, created_by, created_at, last_updated_by, last_updated_at, is_admin FROM users
ORDER BY created_at
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastUpdatedBy,
			&i.LastUpdatedAt,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postUser = `-- name: PostUser :one
INSERT INTO users (
  name,
  email,
  password,
  created_by,
  last_updated_by,
  is_admin
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
) RETURNING id, name, email, password, created_by, created_at, last_updated_by, last_updated_at, is_admin
`

type PostUserParams struct {
	Name          string    `json:"name"`
	Email         string    `json:"email"`
	Password      string    `json:"password"`
	CreatedBy     uuid.UUID `json:"created_by"`
	LastUpdatedBy uuid.UUID `json:"last_updated_by"`
	IsAdmin       int16     `json:"is_admin"`
}

func (q *Queries) PostUser(ctx context.Context, arg PostUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, postUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.CreatedBy,
		arg.LastUpdatedBy,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUpdatedBy,
		&i.LastUpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}
