definitions:
  api.userInfoReqBody:
    properties:
      checkPassword:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
paths:
  /followship/:topicId:
    delete:
      consumes:
      - application/json
      description: DeleteFollowship by toipcId
      parameters:
      - description: topicID(uuid)
        in: path
        name: topicID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      security:
      - BearerAuth: []
      summary: DeleteFollowship by toipcId
      tags:
      - followship
    post:
      consumes:
      - application/json
      description: PostFollowship by toipcId
      parameters:
      - description: topicID(uuid)
        in: path
        name: topicID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"result":{}}'
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: PostFollowship by toipcId
      tags:
      - followship
  /signup:
    post:
      consumes:
      - application/json
      description: User register
      parameters:
      - description: userInfoReqBody
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.userInfoReqBody'
      produces:
      - application/json
      responses:
        "201":
          description: '{"result":"Create user success"}'
          schema:
            type: string
      summary: User register
      tags:
      - system
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
