definitions:
  controller.loginReqBody:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  controller.signupReqBody:
    properties:
      checkPassword:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
  db.PostpostsParams:
    properties:
      content:
        type: string
      created_by:
        type: string
      last_updated_by:
        type: string
      owner_id:
        type: string
      title:
        type: string
      topic_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /followship/:topicId:
    delete:
      consumes:
      - application/json
      description: DeleteFollowship by toipcId
      parameters:
      - description: topicID(uuid)
        in: path
        name: topicID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      security:
      - BearerAuth: []
      summary: DeleteFollowship by toipcId
      tags:
      - followship
    post:
      consumes:
      - application/json
      description: PostFollowship by toipcId
      parameters:
      - description: topicID(uuid)
        in: path
        name: topicID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"result":{}}'
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: PostFollowship by toipcId
      tags:
      - followship
  /login:
    post:
      consumes:
      - application/json
      description: verify user information and issue token
      parameters:
      - description: loginReqBody
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.loginReqBody'
      produces:
      - application/json
      responses:
        "200":
          description: '{"result": "JWT token"}'
          schema:
            type: string
      summary: verify user information and issue token
      tags:
      - system
  /signup:
    post:
      consumes:
      - application/json
      description: User register
      parameters:
      - description: signupReqBody
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.signupReqBody'
      produces:
      - application/json
      responses:
        "201":
          description: '{"result":"Create user success"}'
          schema:
            type: string
      summary: User register
      tags:
      - system
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
