name: Test
run-name: run unit test

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'

      - name: Create .env
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_SERVER_PORT: 8080
          directory: ./
          file_name: .env
          fail_on_empty: false

      - name: Run test
        run: |
          docker-compose -f docker-compose.test.yml up
          docker-compose -f docker-compose.test.yml run gocard make addplugin && make migrateup && make test