name: Test
run-name: run unit test

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'

      - name: Install golang-migrate
        run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: Create .env
        uses: SpicyPizza/create-envfile@v1.2
        with:
          envkey_SERVER_PORT: 8080
          envkey_DB: gocard
          envkey_DBHost: postgres13
          envkey_DBUSER: ${{ secrets.DBUSER }}
          envkey_DBPASSWORD: ${{ secrets.DBPASSWORD }}
          directory: ./
          file_name: .env
          fail_on_empty: false

      - name: Run test
        run: |
          docker-compose -f docker-compose.test.yml build
          docker-compose -f docker-compose.test.yml run --rm gocard make sqlc
          sleep 5
          docker exec postgres13 psql -U gocard -c "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";"
          migrate -path db/migration -database "postgres://${{ secrets.DBUSER }}:${{ secrets.DBPASSWORD }}@localhost:5432/gocard?sslmode=disable" up
          go test -cover ./...